### ISSUE TITLE
Auto-login offline?

### ISSUE THREAD

**Issue by daninthemix** [WombatFromHell/OriginSteamOverlayLauncher#1]
Awesome - love how it shuts Origin after closing the game.

One thing though: I always run Origin offline, and it always makes me type my password. Is there any way your app could force Origin to auto-login, even when offline?

**Comment by WombatFromHell** [comment]
Unfortunately not, Origin uses an OAuth ticket confirmed through their login servers to authenticate that you are the user that owns the previously online Origin account by having you compare your current login to the last used one. Tampering with that process (which is probably against their Terms of Service and likely subject to account termination if they find out) is beyond the scope of this project.
