### ISSUE TITLE
Refresh system tray icons

### ISSUE THREAD

**Issue by bluesky139** [WombatFromHell/OriginSteamOverlayLauncher#13]
I'm using OSOL to launch Origin game from Steam, set Origin as launcher and set a specific game to start, Origin can be killed in several seconds after game exited, this works perfectly except one, the Origin icon still exists in system tray until mouse hover.

So, is it possible to refresh system tray icons?

**Comment by BarterClub** [comment]
I also can say this happens.

**Comment by WombatFromHell** [comment]
Yes, it's possible. I'll add it to my checklist for v1.07.

**Comment by WombatFromHell** [comment]
This should be addressed in [pre-release v1.06d](https://github.com/WombatFromHell/OriginSteamOverlayLauncher/releases/tag/v1.06d).

Let me know if you find any bugs with the method I'm using to clean up the system tray.
