### ISSUE TITLE
Can’t get FIFA 18 to work with Steam Overlay

### ISSUE THREAD

**Issue by AgentRed007** [WombatFromHell/OriginSteamOverlayLauncher#16]
Hey,
Maybe this is not the right place but I can’t get OSOL to work properly. After my first installation it deleted the Origin exe then on the second try the FIFA exe (?). This could be my foult but well after these tries I deactivated that AMD service and it launched but first the Overlay was about Origin and then it wouldn’t start because of failed cloud sync. (It did work before) I cleared the settings and shut down the cloud sync but then it wouldn’t start through OSOL anymore. Only Origin with the Overlay and not FIFA. I can give you any logs you want.
Again I’m not sure if this is a problem caused by me or OSOL so thank you in advance if you could look into that.

**Comment by WombatFromHell** [comment]
Please paste the contents of your OSOL ini file. To paste raw text into Github use a set of three backquotes (ex: \`\`\`) before and after the text.

It should be fine leaving Origin's overlay and cloud syncing turned on although you may need to increase the ```PostGameWaitTime``` in the OSOL ini. Are you sure you're not running any other background applications that could interfere with overlays (like Afterburner/RTSS or a third-party antivirus)?

**Comment by AgentRed007** [comment]
So yeah it was my mistake. I deactivated Bitdefender and closed Wallpaper engine and it worked! I guess the problem was Bitdefender which is kind of strange because I didn’t have any problems with it until now. Thank you! And keep up your great work!

**Comment by WombatFromHell** [comment]
I'm glad you resolved it. Feel free to open another ticket if you need anything else.
