### ISSUE TITLE
Executable arguments limited to 255 characters?

### ISSUE THREAD

**Issue by AlJoelson** [WombatFromHell/OriginSteamOverlayLauncher#17]
When launching an executable with additional arguments, it seems that OSOL cuts off anything beyond 255 characters in length. I'm trying to launch **Elite: Dangerous** via OSOL so that I can automatically start the **_Elite Dangerous Market Connector_** before the game. In order to start ED outside of its native launcher, you need to supply the game with your server auth token via command line as well as including a few extra switches (i.e. /novr to suppress the game starting SteamVR by default).

Would it be possible to extend the length of arguments beyond that?

**Comment by WombatFromHell** [comment]
Good catch on that one. I haphazardly hardcoded StringBuilder() to read from the INI in a max chunk size per line of 255 characters. Oops...

My apologies for not noticing until you mentioned it. I'll fix it immediately and post a hotfix build v1.06b in a bit.

**Comment by AlJoelson** [comment]
No problem, thanks for the quick response. Having the log sitting right there made it easy to identify, and I don't think many people would typically run into this kind of scenario (the token is like 850 characters!)

**Comment by WombatFromHell** [comment]
Hotfix binary posted. I think a 256kb buffer per line should be more than sufficient going forward.

Let me know if this resolves the issue with Elite: Dangerous.

**Comment by AlJoelson** [comment]
Sweet, it works awesomely! Everything is perfect. 👍 

After replacing Elite: Dangerous' launcher with OSOL, I can get straight into the game along with starting the Market Connector through the Steam game entry. Great time saver and essential for Steam Link/Big Picture mode.

**Comment by WombatFromHell** [comment]
Glad to hear it. Good luck out there, Commander. o7
