### ISSUE TITLE
The Crew doesn't hook

### ISSUE THREAD

**Issue by eye-sigil** [WombatFromHell/OriginSteamOverlayLauncher#19]
Added The Crew executable as game exe, upc.exe as launcher. UPlay starts, The Crew starts, overlay doesn't get hooked in.

Disabled all other programs with overlay, tried with both UPlay overlay set on and off in UPlay settings

Using a Steam Controller, so can use that to somewhat diagnose. I set "desktop configuration in launcher" as off in steam controller options. I get my ingame config (can feel the joystick haptics) while still in overlay, got controller button prompts but controller buttons did nothing (found when UPlay warned me about not having UPlay overlay on). When game starts, Steam Controller switches back to desktop configuration.

Closing The Crew closes UPlay. as expected.

**Comment by WombatFromHell** [comment]
I happen to have The Crew. I'll look into it and get back to you ASAP.

**Comment by WombatFromHell** [comment]
I'm not seeing the issue you're describing (I'm testing with an Nvidia card using only the default Windows 10 MSE antivirus with an exclusion for the directory The Crew is in).

Does this issue occur when you launch The Crew normally as a non-steam game from Steam/BPM? If so, it sounds like you may have third party antivirus/antimalware that is interfering with Steam. Disable or uninstall such software temporarily to see if this is the case. If this helps, you may want to see if you can add a folder or executable exclusion for Steam, The Crew, and the UPlay launcher to help prevent interference, or even consider switching to a different antivirus product.

**Comment by eye-sigil** [comment]
Figured it out, unfortunately it seems to be ReShade, which I don't even
notice now since I throw it into every game. Thanks anyways.
