### ISSUE TITLE
MinimizeLauncher doesn't work after game exited.

### ISSUE THREAD

**Issue by bluesky139** [WombatFromHell/OriginSteamOverlayLauncher#21]
I'm using OSOL to launch Origin game from Steam, set Origin as launcher and set a specific game to start.

"MinimizeLauncher" is set to true, Origin can be minimized before game start, but after game exited, Origin is not minimized before it get killed.

**Comment by WombatFromHell** [comment]
Origin brings itself out of a minimized state when the game exits. Not much I can do about that except issue the message to minimize it again before it gets killed, which is honestly kind of pointless given that the window will likely only be hidden for a few seconds before dying.

The launcher window popping up before dying can also be a good thing in some circumstances in case there are fatal issues with cloud syncing.

**Comment by bluesky139** [comment]
Ok, I understand.

I have this thought, I just want to give Origin much more time to sync, sync will be succeeded in most cases, sometime it gets failed, I don't care. So, I want Origin do whatever it want in background and silently exit, just don't bother me. Also, this will more like a Steam game.

It's fine to close this issue if not much we can do.

**Comment by WombatFromHell** [comment]
This should be addressed by commit 3961e81 and v1.06g.
