### ISSUE TITLE
Any way to have the process kill itself after Launch ? 

### ISSUE THREAD

**Issue by PCRulesPSDrools** [WombatFromHell/OriginSteamOverlayLauncher#23]
First off, this is the first solution that has worked in my attempts to get Steam Controller/PS4 controller to be recognized with Xinput in Battlefield 4 allowing me to use a combination of Xinput/direct input/mouse Gyro's. So thanks for that.

Only version " J " works for me, I've tried K and L, they fail to have any result. I'm on Windows 7 Pro btw.

The error "OriginSteamOverlayLauncher.exe has stopped working" keeps popping up quite frequently until I Alt Tab out and kill the OSOL process.  Which oddly leaves everything in perfect order afterwards, Steam is able to maintain Overlay and Controls within the game.  

I'd love to have an option to have the OSOL process kill itself shortly after performing the launch of Battlefield 4. Not only for myself, but for my less PC inclined PC gaming friend who uses a Steam Controller for BF4 and is always complaining about the need to setup direct input controls in non Steam games. Also having to substitute WASD for Analog Sticks can be a killer in some games.

**Comment by WombatFromHell** [comment]
If you haven't already, you might try installing the .NET 4.7.1 Redistributable pack from here: https://www.microsoft.com/en-us/download/details.aspx?id=56115

I assumed most people are using Windows 10 (which includes this redistributable), but I'll make sure to add a note on the README about it.

There isn't a way to kill OSOL automatically after launching a child process yet. I'll add it on my todo list for the next version.

**Comment by WombatFromHell** [comment]
... and it's out! Enjoy!
