### ISSUE TITLE
Confused at installing this

### ISSUE THREAD

**Issue by Erik1223** [WombatFromHell/OriginSteamOverlayLauncher#29]
New to github I really want steam overlay in my games. I'm figuring out so many things right now I'm really stupid sorry. I downloaded git? Do I even need that? Cause I did try downloaded this and there was no executable file seen in the download...it's missing. I have windows 10 and I dont have winrar do I need that? I have .sln file popping up that looks exactly the same file you said to place in game directory but there is no exe to be seen. It's frustrating for me

**Comment by WombatFromHell** [comment]
Where are you trying to download it? You'll want to use the download links found at the top of the [Releases page](https://github.com/WombatFromHell/OriginSteamOverlayLauncher/releases). The most current version of OSOL is [v1.07d](https://github.com/WombatFromHell/OriginSteamOverlayLauncher/releases/download/v1.07d/OriginSteamOverlayLauncher-v1.07d.zip).

Here are the typical steps to install and use OSOL:

1) Unpack the OSOL .exe file from the OSOL archive into the game directory (where the game's executable is located for example).
2) Run the OSOL .exe file from this directory and it will prompt you to choose the path to your game executable (required) and the game launcher (which is optional).
3) Add the OSOL .exe to Steam as a non-Steam game by clicking the "Add a game" button on the bottom left of the Steam window, clicking "Add a Non-Steam Game" and selecting the OSOL .exe file in the path chooser.
4) Name this new non-Steam game shortcut of OSOL (in Steam) whatever you like (such as your game's name)
5) Run this non-Steam game shortcut from the Steam library as any other Steam game
6) Optional: for additional functionality or compatibility options for particular launchers see the OSOL Wiki [FAQ page](https://github.com/WombatFromHell/OriginSteamOverlayLauncher/wiki).

**Comment by WombatFromHell** [comment]
I've moved the instructions listed in this issue ticket into the project README file so other users that might have installation related questions can have them answered on the main project page rather than needing to open a ticket. As such I'll go ahead and close this ticket since it's been over 2 weeks without additional activity.

If you still need assistance with installing and using OSOL feel free to add to this ticket and I'll reopen it.
