### ISSUE TITLE
Origin Steam Overlay Launcher & Mirror's Edge Catalyst

### ISSUE THREAD

**Issue by Zero-Starlight** [WombatFromHell/OriginSteamOverlayLauncher#3]
Attempting to run Mirror's Edge Catalyst with OSOL through Steam results in Origin opening and then after attempting to open Mirror's Edge, crashing silently. Attached are the log for Mirror's Edge and the log created directly after that I believe may hold insight into what went wrong.
[IGO_Log.MirrorsEdgeCatalyst_4960.txt](https://github.com/WombatFromHell/OriginSteamOverlayLauncher/files/1096481/IGO_Log.MirrorsEdgeCatalyst_4960.txt)
[IGO_Log.igoproxy64_4744.txt](https://github.com/WombatFromHell/OriginSteamOverlayLauncher/files/1096482/IGO_Log.igoproxy64_4744.txt)

**Comment by WombatFromHell** [comment]
Could you try reproducing this again and post the IGO_Log.Origin.XXXX.txt file? The logs you posted for this ticket don't show the IGO proxy trying to actually hook anything. The IGO Origin log may have some clues as to what the Origin IGO proxy is doing after Steam hooks into it before the game launches (before it crashes I would suppose).

I'm somewhat suspicious that there may be a configuration issue either in your Origin client or in some other software that may be interfering with Origin hooking the game process. You should at the very least be able to get into the game with one overlay.

In terms of what you can do about the Origin client itself I would recommend resetting your cache if you haven't already. These instructions are helpful for that: http://answers.ea.com/t5/Technical-Issues/Don-t-know-how-to-clear-origin-cache-View-this/m-p/5524669#M215766

**Comment by Zero-Starlight** [comment]
Well, it's working now. Still only have the Steam overlay, but it's working. I believe I had to clear the Origin cache to get it to work, but don't quote me on that.

**Comment by WombatFromHell** [comment]
I'm still in the process of nailing down a reproducible case where the Origin overlay and Steam overlay conflict is (that doesn't involve something I can't control) so I can figure out what options I have for working around it.

If you find any more information you think might be helpful feel free to add it to either of the issue tickets.

**Comment by Zero-Starlight** [comment]
Nevermind, it broke again. Here's the log you asked for, hopefully it helps.
[IGO_Log.Origin_12496.txt](https://github.com/WombatFromHell/OriginSteamOverlayLauncher/files/1099350/IGO_Log.Origin_12496.txt)

**Comment by WombatFromHell** [comment]
I was never able to reproduce this issue. I don't see any reason why this is specific to OSOL in particular. If any new information regarding this issue can be amended to this ticket I'll reopen.
