### ISSUE TITLE
Launching Black Ops 4 doesn't work properly

### ISSUE THREAD

**Issue by rastla** [WombatFromHell/OriginSteamOverlayLauncher#30]
So I set it up for Black Ops 4 like this:
```
LauncherPath=D:\Program Files (x86)\Battle.net\Battle.net.exe
LauncherArgs=--exec="launch VIPR"
LauncherURI=
GamePath=C:\Games\BattleNetApps\Call of Duty Black Ops 4\BlackOps4.exe
```

And first the launcher starts and then Black Ops 4 starts.
But Black Ops 4 can't connect to the online services if it isn't startet through the BattleNET App.

**Comment by WombatFromHell** [comment]
That's odd. I've tested against Overwatch, Hearthstone, Destiny 2, and Heroes of the Storm and the launcher commands seemed to work okay.

I'll investigate and get back to you ASAP.

**Comment by WombatFromHell** [comment]
Could you post your OSOL log file for the game in question when you get a chance?

**Comment by WombatFromHell** [comment]
Since no additional information has been offered to support this ticket after 7 days I'll be closing this ticket. Feel free to provide additional information if you still need support and I'll re-open the ticket and assist.
