### ISSUE TITLE
Dead Space 3 issue

### ISSUE THREAD

**Issue by ryboto** [WombatFromHell/OriginSteamOverlayLauncher#31]
I've got an AMD GPU, but disabled the relive overlay as well as the event overlay and I still cannot get this game to recognize my controller.  I don't have any GPU tuning software aside from the AMD catalyst thing, so could something else be interfering?

**Comment by WombatFromHell** [comment]
Have you double checked if your antivirus or anti-malware doesn't have an option that might interfere with Steam's ability to hook the launcher? Typical options include anti-PUP or memory hook protection features.

Other than that you might try temporarily disabling secondary overlays if you have them like Afterburner's RTSS. If their options aren't set correctly they can prevent other overlays from working.

Aside from that, if this is a clean system, it's pretty difficult to tell what might be interfering without trial and error.
