### ISSUE TITLE
Quit Origin on game exit

### ISSUE THREAD

**Issue by pittrevo** [WombatFromHell/OriginSteamOverlayLauncher#32]
Hello, I'm trying to get Origin to quit on game exit. If the Origin app remains open, it causes functionality issues with the Steam Link. I can see there are PostGameExec= and PostGameExecArgs= options in the ini but cannot find an example of how to use these to quit Origin on game exit.

**Comment by WombatFromHell** [comment]
If you follow the directions on the main project page (see [here](https://github.com/WombatFromHell/OriginSteamOverlayLauncher#how-to-use)) OSOL should cause Origin to behave as you want by default.

In summary:

1) Unpack the OSOL archive to any directory (usually the directory of the game you want to use it with).
2) Run `OriginSteamOverlayLauncher.exe` and follow its prompts to choose the Launcher (in this case Origin's .exe file) and Game executables. OSOL will prompt you to run it again once you've done this.
3) Add a non-Steam game shortcut to Steam, pointing it at the OSOL .exe file you just configured.
4) Run this new non-Steam game shortcut in Steam, then exit the game to confirm that Origin (or whichever launcher you chose) will exit upon exiting the game.

**Comment by pittrevo** [comment]
Thanks. Misunderstood that the launcher selection dialog was for the Origin executable - thought it was an option for games with their own launcher.
