### ISSUE TITLE
Origin stays open after game exit

### ISSUE THREAD

**Issue by squatch04** [WombatFromHell/OriginSteamOverlayLauncher#34]
Hello,
I have tested with both Titanfall 2 and Apex Legends. Origin launches and both games execute fine, but Origin stays open after game exit.

Here is my INI settings:
>[Paths]
LauncherPath=C:\Program Files (x86)\Origin\Origin.exe
LauncherArgs=
LauncherURI=
GamePath=D:\Origin\Apex\r5apex.exe
GameArgs=
MonitorPath=
DetectedCommandline=
[Options]
LauncherMode=Normal
PreLaunchExec=
PreLaunchExecArgs=
PostGameExec=
PostGameExecArgs=
PreGameLauncherWaitTime=12
PostGameWaitTime=7
PostGameCommandWaitTime=7
ProxyTimeout=3
ProcessAcquisitionTimeout=300
ReLaunch=True
SkipLauncher=False
DoNotClose=False
ForceLauncher=False
MinimizeLauncher=False
CommandlineProxy=False
ElevateExternals=False
GameProcessAffinity=
GameProcessPriority=
TerminateOSOLUponLaunch=False

Here is my log:
>[2/9/2019 6:23:43 AM] [NOTE] OSOL is running as: OriginSteamOverlayLauncher
[2/9/2019 6:23:44 AM] [OSOL] Attempting to start the launcher: C:\Program Files (x86)\Origin\Origin.exe
[2/9/2019 6:23:44 AM] [OSOL] Searching for valid process by name: Origin
[2/9/2019 6:23:47 AM] [OSOL] Bound to a valid process at PID: 3456 [Origin.exe] in 3 seconds
[2/9/2019 6:23:47 AM] [OSOL] Waiting 12s for launcher process to load...
[2/9/2019 6:23:59 AM] [OSOL] Launching game, cmd: D:\Origin\Apex\r5apex.exe 
[2/9/2019 6:23:59 AM] [OSOL] Searching for valid process by name: r5apex

**Comment by WombatFromHell** [comment]
I'm working on this issue right now. It's due to EAC.

**Comment by squatch04** [comment]
Looking forward to a fix. Thanks for the response.

**Comment by WombatFromHell** [comment]
Please try v1.07g pre-release now available on the releases page and let me know if you still experience this issue.

**Comment by squatch04** [comment]
Hi, version v1.07g pre-release fixes this issue for me. Origin closes after game exit now. Tested with Apex Legends.

Thanks

**Comment by WombatFromHell** [comment]
Glad to hear it. I'll go ahead and close this ticket, but if you see any additional errant behavior feel free to respond to the closed ticket and I'll reopen it.
