### ISSUE TITLE
Any way to make OSOL work with Star Citizen?

### ISSUE THREAD

**Issue by Nichodeamus** [WombatFromHell/OriginSteamOverlayLauncher#35]
So, I was wondering if there is any way to make OSOL work fully automatically, with the Star Citizen launcher (RSI Launcher) and game, so that I can launch Star Citizen from a shortcut in Steam?

As it is, I got it working...   BUT, after steam starts OSOL, and OSOL starts the launcher, then I have to manually click the 'launch game' button inside the launcher, to get it to start up the actual game...  Otherwise the game starts up and then crashes with an error message saying it couldn't find any user information.

Is there any way to make OSOL basically click that button for me?  So far as I know, there are not any command line options for the launcher..  :(

The Star Citizen Launcher:
![starcitizenlauncher1](https://user-images.githubusercontent.com/47490878/52529595-c0fab480-2cb1-11e9-9488-4cf0c2e5ff12.jpg)

Star Citizen Startup/Loading Screen:
![starcitizengamestartup1](https://user-images.githubusercontent.com/47490878/52529603-e1c30a00-2cb1-11e9-83e4-6895f1d2b374.jpg)

**Comment by WombatFromHell** [comment]
The short answer: as far as I know, there is probably no way to make this work well without causing security issues.

The long answer: OSOL does support some launchers that cache user credentials. See the OSOL project Wiki's instructions on "Authenticating Launchers". It's unlikely this will work on Star Citizen's launcher but it's worth a shot.

**Comment by Nichodeamus** [comment]
I read the section of the wiki about 'authenticating launchers', and I followed the instructions there, but it did not exactly work.  :(     /sad

According to OSOL's log, the detected command line arguments are blank.  And when it tried to shutdown and relaunch the game with the proxied command line, the launcher immediately responded as if the game had crashed, asking me to verify the game's files.

The odd thing is that the game DID in fact restart, and the game itself ran fine, just as if I had started it by clicking the 'launch game' button.  It let me play online, logged into my own account, and did not give me any errors.  But meanwhile, the launcher was sitting there showing me that the game had crashed.

I guess I'll look into maybe trying to figure out how to build a script with autohotkey, to move the mouse over the launch button, and click it....  :(

**Comment by WombatFromHell** [comment]
In that case, you could wire that command into OSOL by using the `PreLaunchExec` variable in the ini. This is also on the Wiki.

Assuming you're using a Steam Controller (or at least Steam Input) I'm not sure why you wouldn't just use the mouse input from your Desktop Config to click on the launcher button.

**Comment by Nichodeamus** [comment]
I'm not using a steam controller.  I don't own one of those, because I tried one that a friend bought, and it was just to weird as controller pads go.

I do own and use both a PS4 (DualShock4) and Xbox One controllers, but I don't use either one of them for this particular game.  In star citizen I just use keyboard and mouse.  For the games where I use the PS4 controller, I have a nifty little background program called DS4windows, which emulates a standard xbox controller because about 99% of all PC games expect that to be your controller.

I've never really even tried using the steam input mapping stuff...  Is there some way to make steam click the damned button?   I mean without actually using a steam controller?

**Comment by WombatFromHell** [comment]
I wish I could be of more help, but I don't own Star Citizen so I can't test against it. AutoHotkey should work fine for simply clicking on a specific spot inside a launcher window.
