### ISSUE TITLE
Battle.net launcher detection is busted

### ISSUE THREAD

**Issue by AcidWeb** [WombatFromHell/OriginSteamOverlayLauncher#36]
Currently calling launcher with `--exec="launch WoW"` only start the launcher not the game itself. 
After launcher is ready it need to be started once more with `--exec="launch WoW"` to start the game. 

So correct config in this case look like this:
```
LauncherPath=C:\Path\To\Launcher\Battle.net.exe
LauncherArgs=--exec="launch WoW"
GamePath=C:\Path\To\Launcher\Battle.net.exe
GameArgs=--exec="launch WoW"
MonitorPath=C:\Path\To\World of Warcraft\_retail_\Wow.exe
```

OSOL can't start `Wow.exe` directly as it will not receive auth data from Battle.NET client.

**Comment by WombatFromHell** [comment]
Try the pre-release v1.08a build in the releases section and let me know if it addresses this issue.

**Comment by AcidWeb** [comment]
It is not.

**Comment by WombatFromHell** [comment]
This behavior sounds like OSOL is not detecting the Battle.net launcher properly. When Battle.net is detected OSOL uses different launch logic (it doesn't call the game path manually).

I'll look into it. I may need to add an optional override in the OSOL .ini to force OSOL to use that special logic in case the launcher window details change between releases

**Comment by WombatFromHell** [comment]
Confirmed. OSOL's launcher detection isn't working properly. ETA on a fix is "soon".

**Comment by WombatFromHell** [comment]
Try the pre-release v1.08b build that I just pushed to the releases page and let me know if it fixes the problem for WoW. I only have Overwatch installed at the moment to test against.

**Comment by AcidWeb** [comment]
I can confirm that issue is fixed. Settings provided in wiki now work correctly.
