### ISSUE TITLE
Assassin's Creed: Origins

### ISSUE THREAD

**Issue by StrungOut** [WombatFromHell/OriginSteamOverlayLauncher#38]
Hey mate, 

I have Assassin's Creed Origins running by loading using OSOL and the upc.exe except steam overlay doesnt seem to work at all, no response from pushing the steam button on controller. 
I have tried with and without uplay overlay.
Attempted turning off Allow desktop configuration in launcher (under AC:O manage shortcut -> controller options).
Tried changing base desktop configuration to mimic a gamepad or similar.

My setup is pc -> steam link -> steam controller connected to link. 
Either way I am not able to access steam overlay by pushing the steam button and seems to be running as a desktop style config no matter what.
My next step was to try glosc which it seems to work but causes low fps

Thanks,

**Comment by WombatFromHell** [comment]
First step is to run through common sources of problems. See here: https://github.com/WombatFromHell/OriginSteamOverlayLauncher/wiki/Steam-Overlay-Troubleshooting

Let me know if any of those help at all.

**Comment by StrungOut** [comment]
Thanks, I previously didn't see this section. 
I am running an AMD card and the AMD External Events Utility proved to be the issue. 
I guess the current workaround is stopping the service whenever I want to use one of the games outside of steam. Thanks for the help

**Comment by WombatFromHell** [comment]
You're quite welcome. If you need any additional help feel free to comment on this ticket. I'll go ahead and close it in the meantime.
