### ISSUE TITLE
Close the launcher after the game has stopped running

### ISSUE THREAD

**Issue by StoneColeQ** [WombatFromHell/OriginSteamOverlayLauncher#39]
Could we see a feature of closing the launcher, Origin, Epic Games, etc, after the game such as Apex Legends has been closed?

Currently steam still shows the game running until the launcher is closed.

**Comment by WombatFromHell** [comment]
This behavior is one of the primary reasons OSOL was originally created. What you're describing sounds like a bug or unintended behavior.

Could you post your OSOL config and log files (the .ini and .txt found in the directory you've run OSOL from) or link them from something like Pastebin so I can help diagnose the problem?

**Comment by StoneColeQ** [comment]
Here what I have for both Apex Legends and Fortnite: https://pastebin.com/Qyu5rF72

**Comment by WombatFromHell** [comment]
What version are you running? From the logs it looks like the 1.07 branch. Could you try using the latest pre-release version? It has many fixes for Epic launcher and Apex.

**Comment by StoneColeQ** [comment]
I can in about 30 min

**Comment by StoneColeQ** [comment]
Yes it all works now. Thank you
