### ISSUE TITLE
Uplay Support

### ISSUE THREAD

**Issue by Sixoul** [WombatFromHell/OriginSteamOverlayLauncher#4]
Opens Uplay but doesn't start the game.

**Comment by WombatFromHell** [comment]
I'll investigate and try to get some fixes out for this as soon as I can. Could you post your OSOL log file from when you tried and failed to launch a Uplay game?

**Comment by WombatFromHell** [comment]
Try the [beta build](https://github.com/WombatFromHell/OriginSteamOverlayLauncher/releases/tag/v1.04-beta) and let me know if it fixes this issue.

**Comment by Sixoul** [comment]
Beta Build works. Going to try again to see if it was because I had the wrong .exe selected.

**Comment by WombatFromHell** [comment]
I'm unable to reproduce that behavior. The behavior I see is as follows: the launcher opens (Steam registers playtime starting at this point), then the game opens (tested with Rainbow Six Siege, The Division, and The Crew), then the Steam overlay hooks in on top of the UPlay overlay, then I close the game, and the launcher ("upc.exe" in this case) closes cleanly and Steam registers the game as closed after about 6 - 10 seconds.

If you find an application that doesn't behave as expected then please feel free to add on to this ticket.
