### ISSUE TITLE
Application Icon

### ISSUE THREAD

**Issue by CriticalComposer** [WombatFromHell/OriginSteamOverlayLauncher#40]
This application has no icon so I submit this. I need no credit but if you'd prefer you can add CriticalComposer as a contributor. I have included two versions, with and without text.

![osol_icon](https://user-images.githubusercontent.com/22335399/56378164-331fd600-61da-11e9-9693-6c40f46f4eae.png)
![osol_icon_no_text](https://user-images.githubusercontent.com/22335399/56378168-34e99980-61da-11e9-8a1c-515598e53cbd.png)

**Comment by WombatFromHell** [comment]
The icon without text will probably look cleaner. I'll get a build together incorporating the new icon as soon as I can (hopefully this afternoon). It's only fair to include credit for contributions so I'll be adding a blurb on the project page and included project docs as well.

**Comment by WombatFromHell** [comment]
I notice that the icon doesn't fit the ICO resource file rules for Visual Studio projects. The icon needs to be in 1:1 ratio and no larger than 96x96 or 256x256 (for Vista or higher) in order to display properly. Could you rescale it on your end and post at least the 96x96 version?

**Comment by CriticalComposer** [comment]
Here ya go.

![osol_icon_96](https://user-images.githubusercontent.com/22335399/56382713-05d92500-61e6-11e9-8154-feb9cfce5f99.png)
![osol_icon_256](https://user-images.githubusercontent.com/22335399/56382718-07a2e880-61e6-11e9-8592-10a30d700cb3.png)

**Comment by WombatFromHell** [comment]
Thanks for the contribution! I've added a credit to the project and changelog, as well as pushed a new stable release incorporating the change.

**Comment by WombatFromHell** [comment]
You're free to close this ticket whenever you get an opportunity to test the new version and everything checks out.
