### ISSUE TITLE
Origin Fifa - Mouse wont disappear

### ISSUE THREAD

**Issue by ListGrey** [WombatFromHell/OriginSteamOverlayLauncher#47]
Hi,

I like and use OSOL a lot at my living room while my PC is in the cellar. It works mostly perfect, having only one issue with FIFA on Origin. I use FIFA 2018 but tested it on FIFA 2020 DEMO as well.

After launching it the mouse cursor wont disapper and sticks at the middle of the screen. The controllers (XBOX 360 Controllers connected to steam link) work fine.

Any help or info would be appreciated.

Sorry for my bad english since I am not a native speaker.

Greetings

ListGrey

**Comment by michaelphagen** [comment]
You can use a steam chord press to move the mouse via the right stick. Just 
hold the Xbox button and use the right stick to move the cursor, it should 
work by default.

**Comment by ListGrey** [comment]
Thx a lot, that solves the "issue" for me.

I dont know if the behaviour of OSOL in this case is interesting in any way for development - when starting the game from steam directly (with the nonsteam-shortcut) the mouse disappears - only when starting from big picture mode via steam link that happens.

Thx a lot for your excellent work,

Greetings
