### ISSUE TITLE
Unable to launch Cemu

### ISSUE THREAD

**Issue by lowvyn** [WombatFromHell/OriginSteamOverlayLauncher#48]
Firstly, thanks for OSOL. It's really convenient and solved a lot of my issues with playing non-Steam games on the Steam Link.

I'm trying to get OSOL to launch Cemu, following the steps listed in the Wiki, but for some reason Cemu never gets launched. When setting GamePath to my Cemu executable, nothing happens (other than the OSOL process being run).

Thanks in advance for any help provided!

**Comment by michaelphagen** [comment]
It may be easier to launch your games from CEMU without OSOL. OSOL is 
not necessary for this application.

Just make a shortcut in steam to your CEMU executable, then go into 
properties and edit the target to include -f and -g, then the path to 
the game you want to launch (ex. "A:\Program Files\CEMU\Cemu.exe" -f -g 
"R:\Wii U\Captain Toad Treasure Tracker\code\Kinopio.rpx")

________________________________

Michael Hagen
/Recorded Music Technician 
<https://tisch.nyu.edu/about/directory/clive-davis-institute/1257736403>/

Clive Davis Institute of Recorded Music
Tisch School of the Arts
New York University
370 Jay St, #562B
Brooklyn, NY 11201
/914-299-3142 <tel:9142993142>/

**Comment by lowvyn** [comment]
Yeah, but I'd like to use some of OSOL's pre/postlaunch functionality as well as the added benefit of being able to launch the Steam gyro for CEMU hook executable from the couch.

**Comment by WombatFromHell** [comment]
I'll look into this issue this afternoon and get back to you as soon as I can. Thanks for taking the time to report it.

**Comment by WombatFromHell** [comment]
I can confirm that there is a bug with how OSOL v1.09f handles a blank `LauncherPath`, as a workaround please use the `SkipLauncher=True` variable in the OSOL .ini file you're launching from. This should work as you expect.

I'll try to get this issue fixed in the next OSOL release.

**Comment by lowvyn** [comment]
> I can confirm that there is a bug with how OSOL v1.09f handles a blank `LauncherPath`, as a workaround please use the `SkipLauncher=True` variable in the OSOL .ini file you're launching from. This should work as you expect.
> 
> I'll try to get this issue fixed in the next OSOL release.
> 
> (Edit: In the meantime, I'll add a blurb on the Wiki about the workaround referenced in this ticket.)

Thanks so much for your reply. I'm not sure if the issue lies entirely with a blank `LauncherPath`, seeing as how I've tried setting the Steam Gyro for CemuHook .exe as the launcher to launch Cemu with and the Steam Gyro executable opens but Cemu does not.

**Comment by WombatFromHell** [comment]
I've just pushed a hotfix release (v1.09g) that addresses this and a few other issues. Let me know if it resolves your problem.

**Comment by lowvyn** [comment]
Aye I'll check it out soonest I can.

**Comment by lowvyn** [comment]
Hey, everything’s working great. Thanks for the hotfix! Really appreciate all the time and effort put into this project.
