### ISSUE TITLE
Allow Origin to sync

### ISSUE THREAD

**Issue by SubSonix** [WombatFromHell/OriginSteamOverlayLauncher#5]
First of all. Thank you!!! Been looking  for something like this for a long time :)

As for the "issue" - Origin doesn't seem to get the chance to sync files:

"Unable to sync Cloud Storage data"

"A recent sync with the cloud has been interrupted or a sync is currently in progress on another computer. Please try again later."

Would love an option to delay the client shut-down slightly to allow for syncing after closing a game.

**Comment by WombatFromHell** [comment]
I'll add an option for configuring the post-game sync time to the INI so the user can change the wait time for games that have large saves and/or slower connections.

Thanks for the suggestion!

**Comment by SubSonix** [comment]
No problem, thank you for looking into it :)

**Comment by WombatFromHell** [comment]
This issue should be fixed by pre-release v1.05b, let me know if it works as expected.

**Comment by SubSonix** [comment]
This definitely seems to be working as intended. Thanks :)

**Comment by Zenteck** [comment]
I know this is the wrong place and probably against github etiquette, but I had to register to thank you for this piece of work. My 10+ year old xbox 360 controller finally died on me today, but with this I no longer need it. Lifesaver!
