### ISSUE TITLE
Keep Battle.net open but detect if game runs

### ISSUE THREAD

**Issue by TomberWolf** [WombatFromHell/OriginSteamOverlayLauncher#51]
Hey,

many thanks for this great work!
I'm wondering if it's possible to keep the Battle.net Launcher open but let OSOL detect if the is closed.
I don't want to close Battle.net to keep my games updated automatically by it.

Thanks

Tom

**Comment by WombatFromHell** [comment]
OSOL wasn't really designed with this sort of thing in mind, but you can try setting `CloseLauncher=False` and `ReLaunch=False` inside the `OriginSteamOverlayLauncher.ini` found in the directory you ran OSOL from.

**Comment by TomberWolf** [comment]
I tried that before but it doesn't work. Too bad. 😕
