### ISSUE TITLE
Issue with ReadMe.md/Instructions

### ISSUE THREAD

**Issue by BenjaminHunt** [WombatFromHell/OriginSteamOverlayLauncher#52]
In the "How to Use" Section of your readme.md, it clearly states "Run the OSOL .exe file from this directory." However, I do not see an OSOL.exe file. I do not see an executable file anywhere in the project.

Was it removed? Renamed? Is this step still necessary?

**Comment by WombatFromHell** [comment]
It's on the Releases page: https://github.com/WombatFromHell/OriginSteamOverlayLauncher/releases
