### ISSUE TITLE
Detroit: Become Human -- Steam Link Black Screen

### ISSUE THREAD

**Issue by Irastris** [WombatFromHell/OriginSteamOverlayLauncher#54]
After struggling to get D:BH to recognize my game controller, I stumbled across this project. After a little bit of troubleshooting, mostly involving moving OSOL outside of the game dir, it launches with full controller support.

Now, however, I'm getting a black screen when also trying to remote play. Could this have anything to do with the game being a Vulkan title? I know it's a little bit outside of this project's scope, but I wanted ask just in case.

Thanks.

**Comment by WombatFromHell** [comment]
You may need to try using GloSC if the Steam overlay on its own doesn't work properly with the game in question.

Fortunately, you can still use OSOL's launcher management with GloSC. Just add the path of your OSOL launcher to a GloSC target and then use the GloSC-created shortcut from Steam.

**Comment by Irastris** [comment]
The Steam overlay works fine, it's the streaming portion that dies. I forgot to mention that I have an AMD GPU, but I've already disabled the external events service.

If I look at my monitor, the game is rendering perfectly plus overlay, full controller support.
If I look at my TV with the Steam Link, it's either frozen on a black screen or a single frame of the game.

**Comment by WombatFromHell** [comment]
I don't personally own a Steam Link but I have used the Remote Play function a few times and generally if the Steam overlay functions then the host should be able to stream the game as well.

I'll ask around and get back to you.

**Comment by Irastris** [comment]
It definitely seems like an issue with OSOL rather than the Steam Link as a whole. If I just launch Detroit with Steam, which causes the controller and overlay to not function, it will display Detroit just fine.

**Comment by Irastris** [comment]
I believe the issue may be with the Steam Overlay entirely. It appears to maybe not support however Quantic Dream is doing fullscreen/borderless. A workaround is to set the game to a maximized window at the cost of a lower capture quality. Between video compression and sitting couch distance away, however, it will suffice.

My mistake.

**Comment by michaelphagen** [comment]
> GloSC is outside of my scope as I'm attempting to use a standard Xbox controller.

GloSC was created to allow the steam controller to work in any non-steam title, but it allows steam input (which is what your Xbox controller is using when you launch games with the overlay enabled) in any game, regardless of controller type.

Definitely give it a shot if you haven't already

**Comment by Irastris** [comment]
> GloSC ... allows steam input ... in any game, regardless of controller type.

Ah, interesting. They certainly don't make that clear on their page.

Either way, after settling for my workaround, the game was a stuttering mess despite meeting system requirements, go figure. Getting real sick of things like that happening as a paying customer.

**Comment by michaelphagen** [comment]
Is the game a "stuttering mess" regardless of whether or not you are streaming?

**Comment by Irastris** [comment]
> Is the game a "stuttering mess" regardless of whether or not you are streaming?

Indeed, though interestingly enough the demo was perfect.

**Comment by MartySouth** [comment]
> After struggling to get D:BH to recognize my game controller, I stumbled across this project. After a little bit of troubleshooting, mostly involving moving OSOL outside of the game dir, it launches with full controller support.
> 
> Now, however, I'm getting a black screen when also trying to remote play. Could this have anything to do with the game being a Vulkan title? I know it's a little bit outside of this project's scope, but I wanted ask just in case.
> 
> Thanks.

I'm struggling to get D:BH run via Steam. Could you elaborate on what you did to get it done beside "moving OSOL outside of the game dir"?

**Comment by Irastris** [comment]
> Could you elaborate on what you did to get it done beside "moving OSOL outside of the game dir"? Are there special arguments I should enter into "OriginSteamOverlayLauncher.ini"?

Simply follow https://github.com/WombatFromHell/OriginSteamOverlayLauncher/wiki/Epic-Games-Launcher

**Comment by MartySouth** [comment]
> > Could you elaborate on what you did to get it done beside "moving OSOL outside of the game dir"? Are there special arguments I should enter into "OriginSteamOverlayLauncher.ini"?
> 
> Simply follow https://github.com/WombatFromHell/OriginSteamOverlayLauncher/wiki/Epic-Games-Launcher

Nope, doesn't work. I tried multiple times, but every time the game fails with a dump-file in the "F:\Epic Games\DetroitBecomeHuman\"-folder.

**Comment by Irastris** [comment]
I don't know what to tell you, that's all I had to do. Initially, I overlooked the suggestion of removing OSOL from the game dir, which caused EGL to say the game was already running. Pushing OSOL to my portable software directory solved launching for me.

**Comment by WombatFromHell** [comment]
Like I said the other day, if OSOL by itself doesn't work to solve the issue then you might try combining OSOL with GloSC; OSOL for launcher management, and GloSC as an overlay workaround so Steam's BPM doesn't cause the game itself to crash. This is also sometimes necessary for Origin/UPlay games, as the launcher's overlay conflicts with Steam's and either one will refuse to function. GloSC sort of solves that problem by letting Steam's overlay hook into a separate window instead.

**Comment by MartySouth** [comment]
This all is too much hassle for a game I don't even need an overlay. I added iexplorer.exe as a non-steam game and the game url as arguments to get it run. I also disabled the overlay in Steam via BPM to avoid it conflicting with the EGL.

**Comment by MartySouth** [comment]
This all is too much hassle for a game I don't even need an overlay. I added iexplorer.exe as a non-steam game and the game url as arguments to get it run. I also disabled the Steam's overlay via BPM to avoid it conflicting with the EGL.

**Comment by MartySouth** [comment]
This all is too much hassle for a game I don't even need an overlay. I added iexplorer.exe as a non-steam game and the game url as arguments to get it run. I also disabled the Steam overlay via BPM to avoid it conflicting with the EGL.
