### ISSUE TITLE
Not an issue, just wondering how to use this with RDR2?

### ISSUE THREAD

**Issue by SubSonix** [WombatFromHell/OriginSteamOverlayLauncher#56]
Ass above, non steam version of the game.

Thanks in advance :)

**Comment by adamlweaver** [comment]
I like OSOL a lot, but with RDR2 I had better luck with GLOSC (https://alia5.github.io/GloSC/).

**Comment by SubSonix** [comment]
Turns out you can just add the game exe to steam lol
Been so long since I've been able to do that :P

**Comment by SubSonix** [comment]
Feel free to delete this, actually works just fine.
