### ISSUE TITLE
Origin Overlay not working

### ISSUE THREAD

**Issue by MeridianPY** [WombatFromHell/OriginSteamOverlayLauncher#58]
When I launch either Apex Legends or Titanfall 2 through Steam via OSOL, the Steam Overlay works fine, but the Origin Overlay doesn't show up. If I launch these games through Origin, the Origin Overlay works, but I don't have the Steam Overlay obviously...

The log doesn't give any valuable information as far as I can tell, but here it is:
> [16.01.2020 13:55:04] [NOTE] OSOL is running as: OriginSteamOverlayLauncher
> [16.01.2020 13:55:05] [OSOL] Physical CPUs: 8 / Logical CPUs: 16
> [16.01.2020 13:55:05] [LAUNCHER] Launching process via: C:\Program Files (x86)\Origin\Origin.exe 
> [16.01.2020 13:55:07] [MONITOR@Origin] Process acquired in 1s: Origin.exe [18732]
> [16.01.2020 13:55:07] [OSOL] Launcher detected (type 2), preparing to launch game in 15s...
> [16.01.2020 13:55:22] [LAUNCHER] Launching process via: D:\Origin\Apex\r5apex.exe 
> [16.01.2020 13:55:27] [MONITOR@r5apex] Process acquired in 3,67s: r5apex.exe [12296]
> [16.01.2020 13:56:15] [MONITOR@r5apex] Process exited, attempting to reacquire within 15s: r5apex.exe
> [16.01.2020 13:56:30] [MONITOR@r5apex] Timed out after 15,78s searching for a matching process: r5apex.exe
> [16.01.2020 13:56:30] [OSOL] Game exited, cleaning up...
> [16.01.2020 13:56:30] [OSOL] Found launcher still running, killing it...
> [16.01.2020 13:56:30] [OSOL] Exiting...

I was running the latest release, 1.09f but changed to 1.09h and the issue still persists.

**Comment by MeridianPY** [comment]
I just tested this, and it appears that the Origin Overlay also works when launching the game by running the OSOL exe directly. Apparently the two Overlays don't work together for some reason...

**Comment by WombatFromHell** [comment]
At some point last year Origin started having issues with the Steam overlay. It's out of scope of this project (for now) to deal with overlays directly.

If you absolutely need the Origin Overlay your best bet is to use GloSC (which will also work with OSOL of you want launcher management) since it doesn't require Steam's overlay being hooked into the game itself.
