### ISSUE TITLE
Overlay no longer hooks into Modern Warfare game window

### ISSUE THREAD

**Issue by michaelphagen** [WombatFromHell/OriginSteamOverlayLauncher#60]
As of yesterday, the steam overlay no longer hooks into the Modern Warfare game window using OSOL. The logs say that the game process ModernWarfare.exe has been found, but the overlay only hooks into the battle.net launcher, not the game window. This was working last week, so it may be possible that the game was updated with some kind of anti-cheat that it preventing the Launcher from hooking correctly (like Destiny2 did when on Battle.net).

**Comment by WombatFromHell** [comment]
This is a known issue as of a patch to MW about 3 days ago. There's nothing I can do about it as OSOL relies on Steam's ability to hook into games. Here's hoping the MW devs address it.

Until then, you could try combining OSOL with GLoSC given that GLoSC separates the overlay from the game for better compatibility. You can have GLoSC launch the OSOL shortcut you've already created, and then use the GLoSC created shortcut in Steam.

**Comment by michaelphagen** [comment]
Alright, thanks for that information. I tried to look up this as related to that patch but couldn't find anything. I am currently doing what you said, using GloSC to launch OSOL, but I have always found that the picture isn't as clear (almost like it's running at 30fps) when using GloSC.

Thanks again for all your hard work!
