### ISSUE TITLE
Battle.net slow

### ISSUE THREAD

**Issue by zoppablue** [WombatFromHell/OriginSteamOverlayLauncher#61]
Any idea why it takes 5 seconds to open the game when the launcher opens?

The bnetlauncher does it instantly.

**Comment by WombatFromHell** [comment]
By default OSOL waits for Steam to hook into the launcher before trying to run the game as a workaround for some Steam related overlay issues. It's a configurable timeout found in the OSOL.ini (`PreGameLauncherWaitTime`).
