### ISSUE TITLE
world war z dont recognize gamepad input on steam link

### ISSUE THREAD

**Issue by azerty55** [WombatFromHell/OriginSteamOverlayLauncher#62]
first OSOL is great i can play many of my egs title with steam link on couch 
but i have a game who struggle to launch : world war z 
i can use steam overlay, even remapping BUT i cant use gamepad input on it (abxy triggers...) only KB & M remap, i dont want use my gamepad as KB M
i want play with gamepad implementation , idk if its possible 
Thanks !

**Comment by WombatFromHell** [comment]
Had you tried using GloSC to see if that helps with passing gamepad input to the game?

**Comment by azerty55** [comment]
doesn't work either 
i have overlay but no gamepad input

**Comment by WombatFromHell** [comment]
After some more research it seems that the EGS version of World War Z doesn't support controllers properly. Your best bet is to stick with a KB&M config, unfortunately.

**Comment by azerty55** [comment]
thx for reply ^^
