### ISSUE TITLE
where is the exe file?

### ISSUE THREAD

**Issue by Geralt02** [WombatFromHell/OriginSteamOverlayLauncher#66]
i cant find the exe file, is that supposed to be generated by myself based on the souce code?

**Comment by michaelhagen** [comment]
You can either build the executables from source yourself or get them from https://github.com/WombatFromHell/OriginSteamOverlayLauncher/releases

**Comment by Geralt02** [comment]
okay, how to deal with the easy anti cheat program, it is not working when i try to open an epic game, after the easy anti cheat window pumps out, and the game is not running

**Comment by WombatFromHell** [comment]
Which EGL game are you trying to launch? Check the project Wiki (tab up above) for extra instructions to aid in configuring OSOL for EGL.

**Comment by Geralt02** [comment]
yeah i am trying the url method for that, by the way, the name of the game is called Dauntless.

**Comment by michaelphagen** [comment]
I just tried Dauntless, it's working perfectly. Make sure you've configured the OriginSteamOverlayLauncher.ini correctly. Additionally, you need to make sure that the OriginSteamOverlayLauncher.exe executable is **NOT** in the Dauntless Game folder (as stated on the wiki), or that will prevent the game from launching.

```
LauncherPath=C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win64\EpicGamesLauncher.exe
GamePath=C:\Program Files\Dauntless\Archon\Binaries\Win64\Dauntless-Win64-Shipping.exe
LauncherArgs=
LauncherURI=com.epicgames.launcher://apps/Jackal?action=launch&silent=true
```
