### ISSUE TITLE
There is no .exe

### ISSUE THREAD

**Issue by BarterClub** [WombatFromHell/OriginSteamOverlayLauncher#7]
So i dont see a .exe to even use. Is there something im missing?

**Comment by WombatFromHell** [comment]
The latest release archive is on the Releases page: [found here](https://github.com/WombatFromHell/OriginSteamOverlayLauncher/releases).

**Comment by BarterClub** [comment]
Great thanks, Might be stupid just put that in the read me so people like me dont do stupid things.
