### ISSUE TITLE
EA Desktop Randomly Won't Launch Game

### ISSUE THREAD

**Issue by Dr4goonD3mon** [WombatFromHell/OriginSteamOverlayLauncher#81]
Hi, I've using for quite some time this tool to add other launchers to steam However Right now I have an issue with EA Desktop App, the issue is that games won't launch trough steam, i added the steamoriginoverlay.exe to steam, but when I tried to launch the game EA desktop App show me this message.

The game can't be launched.
There's a technic error that prevents the launch
try again later

But days before yesterday, the launcher was working fine. I don't know how to fix it, when launching games from the launcher they work fine
![image](https://user-images.githubusercontent.com/51757963/217092722-aa9a4770-dd46-4412-b993-267cc837df21.png)

**Comment by michaelphagen** [comment]
This is an issue that I've experienced with EA desktop re-launching some games. Can you try closing EA desktop, restarting your computer, and launching the game from steam again?

**Comment by Dr4goonD3mon** [comment]
Already did that, cleaning the cache and nothing works, just today the games where working fine until I restart my pc

**Comment by Dr4goonD3mon** [comment]
New founding, enabling compatibility mode fixes the issue, but the new Steam big picture ui gets broken

**Comment by geekycow** [comment]
I'm seeing the same thing.  Looks like the recent EA Launcher v12.108 update may be the root of the issue and many more issues (plus it's chosen to re-enable itself to start up on boot too, which is naughty.)  I can't get it to launch Dead Space (the original one.)

**Comment by WombatFromHell** [comment]
Just to verify, are you making sure to use the `EADesktop.exe` as the launcher target and `SkipLauncher=True`?

**Comment by Dr4goonD3mon** [comment]
I Tried SkipLauncher=True but when I did that the game won't show the steam overlay and is very annoying

**Comment by geekycow** [comment]
> Just to verify, are you making sure to use the `EADesktop.exe` as the launcher target and `SkipLauncher=True`?

Please accept my apologies.  You were right to verify (in my case) as I hadn't got that right!

Doing as you instruct means my game, Dead Space (the original one), does now launch -- although for the life of me I can't get my XBox 360 gamepad working with it over Steam Link even though it works natively (no matter what the settings for desktop mode, steam overlay or steam controller mode I use.)

So it looks like my issue is maybe different to those experienced by @Dr4goonD3mon .

Thank you for your work on this software BTW.

**Comment by Hanzenl** [comment]
Hello all,

Experiencing an issue. FIFA 22 won't launch anymore with OSOL. Tried replacing the OSOL launcher for Fifa, clearing cache in EA games, choosing Skiplauncher is true. Many many restarts. Nothing works.

Weird thing is that OSOL does still seem to work with all my other EA games. Tried Fifa 20, NFS Heat and NFS Payback and all still launch with OSOL. Any help will be greatly appreciated.

**Comment by WombatFromHell** [comment]
Had you tried moving the OSOL executable outside of the game's directory? Sometimes games/launchers have logic that prevents a non-game executable from launching inside the game's directory tree.

**Comment by WombatFromHell** [comment]
This is primarily an issue with the newer/newest EA launcher versions. It's believed to be a server-side check so there's nothing I can really do about it. Marking this as wontfix. Sorry. :(
