### ISSUE TITLE
Problems with launching The Sims 4

### ISSUE THREAD

**Issue by Dimenarius** [WombatFromHell/OriginSteamOverlayLauncher#82]
When trying to launch The Sims 4 through OSOL, EA Desktop launches but minimizes immediately before I can even see the Library Screen. (I have MinimizeLauncher set to False)

Then when it it's supposed to launch The Sims 4, this error message is displayed: 
![image](https://github.com/WombatFromHell/OriginSteamOverlayLauncher/assets/30260206/2da859f4-8e47-442b-8d4f-7926d39c9e1a)

But The Sims 4 isn't even open. The Task Manager doesn't show the running process. EA Desktop states I'm playing literally "nothing" and after a few minutes the whole launcher closes because of the ProcessAcquisationTimeout.

This only happens with The Sims 4 for some reason. Every other EA Game I have added to Steam with this launcher launches just fine.

The only way to launch The Sims 4 for now is to launch another EA Game through the Launcher first before launching The Sims 4.

This is actually pretty tedious. Any suggestions on how to improve this?

PS: I already checked if AMD is to blame since I am using an AMD GPU but unfortunately the External Services are not the problem here.

**Comment by Andrurodr** [comment]
@Dimenarius I had the same issue with FIFA 22, to fixit in the `OriginSteamOverlayLauncher.ini` i changed the line `AutoGameLaunch` to False.
and you need to have on True `ReLaunch` and `CloseLauncher` too.

When you quit the game make sure to kill originsteamoverlay proccess that is created, if you use it like me to play through steam link after quit, open the steam link menu and pres stop game.

**Comment by Dimenarius** [comment]
Yes, that seems to work around it. The error message still somehow appears but the game is launching and the Steam Overlay is properly injected.

Exiting the game also properly closes EA Desktop as well as expected.

Thanks for the help. It's a bit different now because I now have to click Play on The Sims 4 when EA Desktop launches but oh well...I know that procedure from The Quarry with their 2K Launcher. 

I must get used to it.

**Comment by AliBdeir** [comment]
All this still doesn't work on FIFA 23. Any ideas?
