### ISSUE TITLE
OSOL not finding the epic games launcher process. (EpicGamesLauncher.exe)

### ISSUE THREAD

**Issue by AllenKll** [WombatFromHell/OriginSteamOverlayLauncher#86]
I followed the directions on the wiki.
OSOL is in separate folder.
URI is set in ini file.
I've tried all four EpicGamesLauncher.exe's (in portal and in Launcher directories)and always get the same results.

When I attempt to launch via double clicking the OSOL executable, Epic launcher comes up but game never seems to attempt to launch.

I see in the logs:
```
[7/15/2023 15:14:18] [NOTE] OSOL is running as: OriginSteamOverlayLauncher
[7/15/2023 15:14:19] [OSOL] Physical CPUs: 8 / Logical CPUs: 16
[7/15/2023 15:14:19] [OSOL] Found previous instance of launcher [EpicGamesLauncher.exe], relaunching...
[7/15/2023 15:14:19] [LAUNCHER] Launching process via: C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win64\EpicGamesLauncher.exe 
[7/15/2023 15:16:20] [MONITOR@EpicGamesLauncher] Timed out after 2.01m searching for a matching process: EpicGamesLauncher.exe
[7/15/2023 15:16:20] [OSOL] Launcher could not be acquired within 2.01m, cleaning up...
[7/15/2023 15:16:21] [OSOL] Exiting...
```

I have verified in the task manager that EGL is running... I mean, I can see it is running as it pops up.

Just for the heck of it, I tried setting `ReLaunch=false ` just to see if it made a difference.  It did not.

```
LauncherPath=C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe
GamePath=C:\Program Files\Epic Games\GuacameleeSTCE\Game.exe
LauncherArgs=
LauncherURI=com.epicgames.launcher://apps/f5d9b93771214e4cbd60506539d1cfc6%3Ae00cb149a07646d4a02b259a6f295381%3A25b902f42cf04b17bc8a3db2f7292d58?action=launch&silent=true

```

I haven't even tried through steam, as OSOL won't even launch the game on it's own.

Side note, you can launch the game without EGL running, and so I tried to configure the game in this way, and launch through steam, and while it does launch the game, it is not recognized as a "Remote Play" game.

**Comment by frpnit** [comment]
Seems OSOL is timing out before finding EPIC Launcher process. Have you tried increasing PreGameLauncherWaitTime in your .ini file?

I've set mine to PreGameLauncherWaitTime=15. You can even try higher numbers, depending on your memory, CPU and if you are running on a SSD or HDD.

And, check my post here: https://github.com/WombatFromHell/OriginSteamOverlayLauncher/issues/84
If you close Epic Games and try to open again through OSOL, you can run on the same issue.

**Comment by AllenKll** [comment]
I just ran another test with Task Manager open.   

Double click OSOL..
I see EpicGamesLauncher show up in task manager.
OSOL times out indicating that it can't find a matching process.

This seems like a basic simple thing, and nobody else is seeing it.  There's not many configuration options in the file, so I don't know the issue is.  I believe this is not related to Guacamelee at all, but is an issue with the way OSOL looks for the EpicGamesLauncher.exe process, so I changed the title

Windows 10 if that makes a difference to anyone.

**Comment by AllenKll** [comment]
It actually installs four launcher executables, and I have tried all four of them.  

Either way all launcher processes are called by the same name.  it doesn't find any of them.

**Comment by frpnit** [comment]
On your first log, osol reports that the games is launched by:
 C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win64\EpicGamesLauncher.exe

Try putting that as launcher path. If not working, again, i insist you opening process properties on details tab on task manager. It will show will the current launch path.

**Comment by AllenKll** [comment]
I did, just as you asked.  I put `C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win64\EpicGamesLauncher.exe` as my launcher path,

Also I checked the details on task manager... it's the same.

![image](https://github.com/WombatFromHell/OriginSteamOverlayLauncher/assets/14350666/826a4e9d-3fd3-40df-86bf-96fcd60fc8ae)

**Comment by AllenKll** [comment]
Also another interesting thing.... OSL doesn't exit. until I manually close the epic launcher... so it KNOWs it's there... but it still says it can't find it... very odd.

**Comment by frpnit** [comment]
Oh, that's really strange. Could you please post your last .ini after the updates i told you to do? I will try to figure out what else it could be.

Use details tab on task manager. It's better to force close isolated processes. And, since you have run epic launcher a couple of times, check if there are any epicwebhelper left in there. If so, force close them all before trying to test running your game through osol executable again.

**Comment by AllenKll** [comment]
[OriginSteamOverlayLauncher.ini.txt](https://github.com/WombatFromHell/OriginSteamOverlayLauncher/files/12554335/OriginSteamOverlayLauncher.ini.txt)

**Comment by AllenKll** [comment]
No epicwebhelpers running, no epiclaunchers running.  I tried after a reboot.

**Comment by WombatFromHell** [comment]
That's very odd behavior. I'm testing the latest v1.09i pre-release build from the releases page right now against ABZU and it works fine. What version are you running?

**Comment by AllenKll** [comment]
I'm running Latest - 1.09f  
I suppose I could try the pre-release.  I'll get back to you.

**Comment by AllenKll** [comment]
Well shit.  Looks like the pre-release must have fixed a bug, 'cause it worked.
I'm always a little uneasy with pre-release software, but I guess it solves my issue.

**Comment by WombatFromHell** [comment]
I'm glad you got it resolved.

I'll go ahead and mark the pre-release build as the latest release build to avoid confusion in the future given how much of a time difference there's been between release builds up to v1.09i.
