### ISSUE TITLE
Origin doesn't closes (Battlefront II)

### ISSUE THREAD

**Issue by MetisC** [WombatFromHell/OriginSteamOverlayLauncher#9]
With the 1.05c; The log says "FATAL" and can't find the game .exe process ID.
With the 1.04 says nothing.
In both cases just Origin doesn't closes after the game. Ir remains opened.

With Battlefront I (my other Origin game) it works perfect.

**Comment by WombatFromHell** [comment]
Paste your OSOL ini if you could. It sounds like you're not targetting the right executables.

**Comment by BarterClub** [comment]
Same.

**Comment by MetisC** [comment]
Here
[13/11/2017 23:55:54] [OSOL] Attempting to start the launcher, cmd: C:\Program Files (x86)\Origin\Origin.exe
[13/11/2017 23:55:58] [OSOL] Detected the launcher process window at PID [6172] in 3 sec.
[13/11/2017 23:56:03] [OSOL] Launching game, cmd: D:\Juegos\Origin Games\STAR WARS Battlefront II\starwarsbattlefrontii.exe 

Just stops there. With Battlefront 1 works flawless. Anyway any time I launch your program origin just re-opens so I just close manually the Origin window after playing.
Thanks!

**Comment by WombatFromHell** [comment]
Hmm, so the Origin launcher starts, loads, and then attempts to launch Battlefront 2 at that point. Does the BPM overlay show in the Origin launcher before the game tries to load (unsuccessfully)? If not there could be some sort of overlay issue between Origin and BPM.

Given that I don't have Battlefront 2 to test again, and assuming you're running Windows 10, you could help me immensely by doing the following:

- Enabling the "Command line" column in Windows Task Manager by Right-Clicking the taskbar, selecting "Task Manager"
- Clicking "More Details" on the bottom-left of the window
- Selecting the "Details" tab, right-clicking one of the sorting columns and selecting "Select columns", then picking "Command line" from the list, and then clicking okay
- Launch Battlefront 2 normally and when the game comes up Alt+Tab to the Task Manager window (or use Ctrl+Shift+Esc) and navigate to the "Details" tab then locate the Battlefront 2 executable in the process list and scroll over to the "Command line" column
- Make a note of the exe name and any arguments after it

Comment back on what you find and I'll try my best to investigate. Barring that, however, you could try changing `LauncherMode` in the OSOL ini file. For example, change it **to** `LauncherMode=LauncherOnly` **from** `LauncherMode=Normal` and then manually launch the game in Origin when it starts up.

**Comment by WombatFromHell** [comment]
I'm going to assume this was addressed by releases after v1.06 or fixed by the user. I'll re-open the ticket if there's a specific issue with OSOL or new information is posted in this or another ticket.
